export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    signup: "/auth/signup",
    refresh: "/auth/refresh",
    username: "/auth/username",
  },
  profile: "/users/me",
  files: {
    upload: "/upload/files",
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
  users: { getAll: "/users" },
  customers: { getAll: "/customers" },
  dealerCustomers: { getAll: "/dealer-customers" },
  vehicles: { getAll: "/vehicles", variant: "/vehicle-colors" },
  pdiChecks: { getAll: "/pdi-checks" },
  dealers: { getAll: "/dealers", inventory: "/dealers/inventory" },
  inventories: {
    getAll: "/inventories",
    getByVehicle: "/inventories/by-vehicle",
    getByVehicleColor: "/inventories/by-vehicle-color",
  },
  enquiries: { getAll: "/enquiries" },
  walkInEnquiries: { getAll: "/walkin-enquiries" },
  followUps: { getAll: "/follow-ups" },
  schemes: { getAll: "/schemes" },
  queries: { getAll: "/queries" },
  vehicleEnquiries: { getAll: "/vehicle-enquiries" },
  financers: { getAll: "/financers" },
  tickets: { getAll: "/tickets" },
  technicians: { getAll: "/technicians" },
  dealerTickets: { getAll: "/dealer-tickets" },
  reports: { getAll: "/reports" },
  vehicleModels: { getAll: "/vehicle-models" },
  orders: {
    getAll: "/orders",
    dealers: "/dealer-orders",
    customers: "/customer-orders",
  },
};
